### ISSUE TITLE
IPv4 parsing for v2.0.0

### ISSUE THREAD

**Issue by athanclark** [slamdata/purescript-uri#20]
I'm still a lowly purescript `v0.10.7` user, so the `v2.0.0` tag is the latest applicable for me. However, the fixes made to IPv4 octet parsing recently made were only applied to `>= v3.0.0`. I've made changes to the `v2.0.0` commit, but I can't file a pull request without a backport branch in this repository. Would you be willing to pull my changes into a new version?

https://github.com/athanclark/purescript-uri/tree/v2.0.1

**Comment by garyb** [comment]
I've just created a `v2-backport` branch, if you'd like to submit a PR to that?

**Comment by athanclark** [comment]
Yes please! Just filed in #21
