### ISSUE TITLE
4 build errors: all say "cannot import from module Data.URI.Common"

### ISSUE THREAD

**Issue by metaleap** [slamdata/purescript-uri#37]
Just added to a project via `bower i purescript-uri` (which fetched v4.2.0); then next up, using `purs` repo's current `master` branch (prints as `--version` 0.11.6 dev build) and `pulp build` errored out with:

    * Building project in /home/rox/c/ps/test-pscorefn-src
    Compiling Data.URI.UserInfo
    Compiling Data.URI.Fragment
    Compiling Data.URI.Path
    Compiling Data.URI.Host
    Error 1 of 4:
    
      in module Data.URI.Fragment
      at bower_components/purescript-uri/src/Data/URI/Fragment.purs line 13, column 25 - line 13, column 43
      
        Cannot import value decodePCTComponent from module Data.URI.Common
        It either does not exist or the module does not export it.
        
        
      See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
      or to contribute content related to this error.
      
    Error 2 of 4:
    
      in module Data.URI.Host
      at bower_components/purescript-uri/src/Data/URI/Host.purs line 21, column 25 - line 21, column 34
      
        Cannot import value decodePCT from module Data.URI.Common
        It either does not exist or the module does not export it.
        
        
      See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
      or to contribute content related to this error.
      
    Error 3 of 4:
    
      in module Data.URI.Path
      at bower_components/purescript-uri/src/Data/URI/Path.purs line 25, column 25 - line 25, column 35
      
        Cannot import type PCTEncoded from module Data.URI.Common
        It either does not exist or the module does not export it.
        
        
      See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
      or to contribute content related to this error.
      
    Error 4 of 4:
    
      in module Data.URI.UserInfo
      at bower_components/purescript-uri/src/Data/URI/UserInfo.purs line 9, column 25 - line 9, column 34
      
        Cannot import value decodePCT from module Data.URI.Common
        It either does not exist or the module does not export it.
        
        
      See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
      or to contribute content related to this error.

Could it be Bower mixed up some deps somehow somewhere? Or what could this be about?

**Comment by natefaubion** [comment]
Large parts of the ecosystem will not build using `purs` master, because it has several breaking changes. Please use a tagged release.
