### ISSUE TITLE
Parsing a host that starts with a number

### ISSUE THREAD

**Issue by ethul** [slamdata/purescript-uri#39]
When parsing a URI with a host that starts with a number; e.g., `https://1a.test.com`, the parser fails with the error `Could not match character '.'`. I believe the parser is attempting to parse it as an IP address and failing:

https://github.com/slamdata/purescript-uri/blob/5600a0addaed38688e381f5b96d7f7a870dd88e5/src/Data/URI/Host.purs#L39

If it helps, I noticed the parsing error when upgrading from version 2.0.0 to version 2.0.1. The issue is still present on verson 4.2.2

**Comment by garyb** [comment]
Yeah I think you've identified the exact problem with that line! I think it should be more like:
```
parser = try ipv6AddressParser <|> try ipv4AddressParser <|> regNameParser
```

**Comment by ethul** [comment]
Makes sense. Thanks for taking a look!

**Comment by ethul** [comment]
Thanks!
