### ISSUE TITLE
Change `id` to `identity` in documentation

### ISSUE THREAD

**Issue by janeymunoz** [slamdata/purescript-uri#51]
Relevant since this change to Prelude: https://github.com/purescript/purescript-prelude/commit/2f11d6fe49ff85fd78f351ac99610f6f1693e33a

Instances of `id` in URI documentation: https://github.com/purescript-contrib/purescript-uri/search?q=id&unscoped_q=id

**Comment by garyb** [comment]
Resolved by #52
