### ISSUE TITLE
Query parsing is not stack safe

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-uri#63]
**Describe the bug**
Query parsing is not stack safe.

**To Reproduce**
https://github.com/purescript-contrib/purescript-uri/pull/62/files#diff-13c2757ea68a4334dd767c43e5b0af56d070ec023d849a9d5b01f73f16178083R25

**Expected behavior**
Should not crash.

**Additional context**
Pls.

**Comment by garyb** [comment]
I have a fix for this. The parsers should all switch to `List.maybeRec` / `List.someRec` rather than `Array.maybe` / `Array.some`.
